server:
  port: 8181
eureka:
  client:
    register-with-eureka: true #是否像注册中心注册自身
    fetch-registry: true #是否需要检索服务
    service-url:
      defaultZone: http://127.0.0.1:8180/eureka/,http://127.0.0.1:8182/eureka/
spring:
  application:
    name: peer2
